use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
            .join("windows")
            .join("no-uac.manifest");
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rustc-link-arg-bin=update-doc-registry=/MANIFEST:EMBED");
        println!(
            "cargo:rustc-link-arg-bin=update-doc-registry=/MANIFESTINPUT:{}",
            manifest.display()
        );
    }
    generate_bundled_inventory();
}

fn generate_bundled_inventory() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo::rerun-if-changed=src/packages/bundled-inventory.toml");
    let list_path = manifest_dir.join("src/packages/bundled-inventory.toml");
    let list = fs::read_to_string(&list_path).expect("bundled-inventory.toml readable");
    let inventory = parse_inventory(&list);
    assert!(
        !inventory.roots.is_empty(),
        "bundled-inventory.toml must list at least one package root"
    );

    let mut generated =
        String::from("// @generated by build.rs from src/packages/bundled-inventory.toml\n");
    generated.push_str("pub(crate) const BUNDLED_PACKAGES: &[BundledPackageEntry] = &[\n");
    for root in &inventory.roots {
        emit_package_entry(&mut generated, &manifest_dir, root, true);
    }
    generated.push_str("];\n\n");

    generated.push_str("pub(crate) const BUNDLED_HELPERS: &[BundledPackageEntry] = &[\n");
    for helper in &inventory.helpers {
        emit_package_entry(&mut generated, &manifest_dir, &helper.root, false);
    }
    generated.push_str("];\n\n");

    generated.push_str("pub(crate) const BUNDLED_HELPER_EXPORTS: &[BundledHelperExport] = &[\n");
    for helper in &inventory.helpers {
        for file in &helper.exports {
            let path = manifest_dir.join("packages").join(&helper.root).join(file);
            if !path.is_file() {
                panic!(
                    "helper `{}` export `{}` missing at {}",
                    helper.root,
                    file,
                    path.display()
                );
            }
            generated.push_str(&format!(
                "    BundledHelperExport {{\n        specifier: \"{}\",\n        root: \"{}\",\n        file: \"{}\",\n    }},\n",
                escape_rust(&format!("{}/{file}", helper.root)),
                escape_rust(&helper.root),
                escape_rust(file),
            ));
        }
    }
    generated.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("bundled_packages.rs");
    fs::write(&dest, generated).expect("write bundled_packages.rs");
}

fn emit_package_entry(generated: &mut String, manifest_dir: &Path, root: &str, require_clay: bool) {
    if root.is_empty() || root.contains(['/', '\\']) || root.contains("..") {
        panic!("invalid bundled inventory root `{root}`");
    }
    let manifest_path = manifest_dir
        .join("packages")
        .join(root)
        .join("package.json");
    println!("cargo::rerun-if-changed=packages/{root}/package.json");
    let bytes = fs::read(&manifest_path).unwrap_or_else(|error| {
        panic!("read {}: {error}", manifest_path.display());
    });
    let value: serde_json::Value = serde_json::from_slice(&bytes).unwrap_or_else(|error| {
        panic!("parse {}: {error}", manifest_path.display());
    });
    let name = value
        .get("name")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| {
            panic!("{root}/package.json missing string name");
        });
    let version = value
        .get("version")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| {
            panic!("{root}/package.json missing string version");
        });
    if require_clay && value.get("clay").is_none() {
        panic!("{root}/package.json missing clay metadata");
    }
    generated.push_str(&format!(
        "    BundledPackageEntry {{\n        name: \"{}\",\n        version: \"{}\",\n        root: \"{}\",\n        manifest_fingerprint: \"{}\",\n    }},\n",
        escape_rust(name),
        escape_rust(version),
        escape_rust(root),
        fnv1a64_hex(&bytes),
    ));
}

struct InventoryHelper {
    root: String,
    exports: Vec<String>,
}

struct Inventory {
    roots: Vec<String>,
    helpers: Vec<InventoryHelper>,
}

fn parse_quoted(line: &str, key: &str) -> Option<String> {
    line.strip_prefix(key)?
        .trim()
        .strip_prefix('=')?
        .trim()
        .strip_prefix('"')?
        .strip_suffix('"')
        .map(str::to_string)
}

fn parse_inventory(source: &str) -> Inventory {
    let mut roots: Vec<String> = Vec::new();
    let mut helpers: Vec<InventoryHelper> = Vec::new();
    for (index, line) in source.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(value) = parse_quoted(line, "root") {
            if value.is_empty() {
                panic!("bundled-inventory.toml:{}: empty root", index + 1);
            }
            if roots.iter().any(|root| root == &value)
                || helpers.iter().any(|helper| helper.root == value)
            {
                panic!("bundled-inventory.toml: duplicate root `{value}`");
            }
            roots.push(value);
            continue;
        }
        if let Some(value) = parse_quoted(line, "helper") {
            if value.is_empty() {
                panic!("bundled-inventory.toml:{}: empty helper", index + 1);
            }
            if roots.iter().any(|root| root == &value)
                || helpers.iter().any(|helper| helper.root == value)
            {
                panic!("bundled-inventory.toml: duplicate helper `{value}`");
            }
            helpers.push(InventoryHelper {
                root: value,
                exports: Vec::new(),
            });
            continue;
        }
        if let Some(value) = parse_quoted(line, "export") {
            let Some(helper) = helpers.last_mut() else {
                panic!(
                    "bundled-inventory.toml:{}: export without helper",
                    index + 1
                );
            };
            if value.is_empty() || value.contains("..") || value.starts_with('/') {
                panic!(
                    "bundled-inventory.toml:{}: invalid export `{value}`",
                    index + 1
                );
            }
            if helper.exports.iter().any(|export| export == &value) {
                panic!(
                    "bundled-inventory.toml: duplicate export `{}/{}`",
                    helper.root, value
                );
            }
            helper.exports.push(value);
            continue;
        }
        panic!(
            "bundled-inventory.toml:{}: expected `root`, `helper`, or `export`",
            index + 1
        );
    }
    for helper in &helpers {
        if helper.exports.is_empty() {
            panic!(
                "bundled-inventory.toml: helper `{}` needs at least one export",
                helper.root
            );
        }
    }
    Inventory { roots, helpers }
}

fn fnv1a64_hex(bytes: &[u8]) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

fn escape_rust(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
