import {
  defineButton,
  defineEditorView,
  defineFlex,
  defineLabel,
  defineList,
  definePanel,
  defineStack,
  publishTree,
} from "clay:sdui";

const root = defineFlex({
  id: "root",
  direction: "row",
  children: [
    definePanel({
      id: "workspace-panel",
      title: "Workspace",
      children: [
        defineStack({
          id: "workspace-stack",
          children: [
            defineLabel({ id: "status-label", text: "Runtime SDUI ready" }),
            defineButton({
              id: "refresh-button",
              label: "Refresh",
              action: { commandId: "workspace.refresh", arguments: { force: true } },
            }),
            defineList({
              id: "document-list",
              items: [
                {
                  id: "active-document",
                  label: "Document 1",
                  detail: "Generated by tests/fixtures/configuration/sdui-init.js",
                  action: { commandId: "document.open_recent" },
                },
              ],
            }),
          ],
        }),
      ],
    }),
    defineEditorView({ id: "editor", documentId: 1, expectedVersion: 1 }),
  ],
});

await publishTree(root);
