#!/usr/bin/env python3
"""Snapshot the real Clay workspace tree + a few real file bodies into
workspace-data.js, so both Workspace screens (and both Coding Agent screens)
read one source of truth.

Run from anywhere:  python3 design-artifacts/tools/make-workspace-data.py

Only real repository data goes in: entry names, item counts and file text are
read from the checkout. Files that are not snapshotted are still listed in the
tree; opening them shows a "not bundled in this artifact" note rather than
invented content.
"""
from __future__ import annotations

import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[2]
ARTIFACTS = pathlib.Path(__file__).resolve().parent.parent
# Every artifact folder that already ships a snapshot is refreshed in place, so
# approved and prototype copies never drift apart.
OUT_DIRS = sorted(
    path.parent for path in ARTIFACTS.glob('*/*/workspace-data.js')
)

# Directory -> its real children, as repository-relative paths. Only these
# directories expand in the artifact; every other row stays a counted,
# collapsed folder exactly like the shipped tree.
def _children(rel: str, names: list[str]) -> list[str]:
    return [f'{rel}/{name}' for name in names]


def _listing(rel: str, limit: int | None = None) -> list[str]:
    names = sorted(entry.name for entry in (REPO / rel).iterdir())
    return names[-limit:] if limit else names


CHILDREN: dict[str, list[str]] = {
    '.agents': ['.agents/skills'],
    '.agents/skills': _children('.agents/skills', _listing('.agents/skills')),
    'decision-logs': _children('decision-logs', _listing('decision-logs', 6)),
    'docs': _children('docs', _listing('docs')),
    'packages': _children('packages', _listing('packages')[:11]),
    'src': _children('src', _listing('src')),
    'tests': _children('tests', _listing('tests')[:6]),
}

# Root order mirrors the shipped screenshot, which sorts dotfiles first, then
# the directory blocks, then loose files.
ROOT_ORDER = [
    '.agents', '.cargo', '.github', '.gitignore', '.ignore', '.impeccable',
    '.mcp.json', 'AGENTS.md', 'Cargo.lock', 'Cargo.toml', 'DESIGN.md',
    'PRODUCT.md', 'README.md', 'VENT.md', 'benches', 'build.rs', 'clay-agent',
    'decision-logs', 'distribution', 'docs', 'examples', 'frontend', 'graft',
    'packages', 'plans', 'roadmap.md', 'runtime', 'scripts', 'skills-lock.json',
    'src', 'src-tauri', 'test-plan', 'tests', 'tools', 'windows',
]

# Optional tail: extra top-level entries present in the checkout but not in the
# reference screenshot are appended so the tree still describes the real repo.
SNAPSHOT_LIMIT = {
    'VENT.md': ('## 26-08-15 04:01', None),
    'README.md': (None, 24),
    'AGENTS.md': (None, 22),
    'DESIGN.md': (None, 30),
    'PRODUCT.md': (None, 24),
    'Cargo.toml': (None, 24),
    '.gitignore': (None, 16),
    'build.rs': (None, 14),
}


def count_label(name: str) -> str:
    entries = [e for e in (REPO / name).iterdir() if e.name != '.git']
    if not entries:
        return ''
    return f"{len(entries)} item" + ('' if len(entries) == 1 else 's')


def snapshot(rel: str) -> str:
    text = (REPO / rel).read_text(encoding='utf-8')
    until, limit = SNAPSHOT_LIMIT[rel]
    if until:
        cut = text.find(until)
        text = text[:cut]
    if limit:
        text = '\n'.join(text.splitlines()[:limit]) + '\n'
    return text.rstrip() + '\n'


def node(entry: str) -> dict:
    # type comes from the filesystem so nested paths are classified correctly
    is_dir = (REPO / entry).is_dir()
    item = {'id': entry, 'type': 'dir' if is_dir else 'file'}
    if is_dir:
        label = count_label(entry)
        if label:
            item['count'] = label
        kids = CHILDREN.get(entry, [])
        if kids:
            item['children'] = [node(kid) for kid in kids]
    return item


def main() -> None:
    present = {p.name for p in REPO.iterdir()}
    order = [name for name in ROOT_ORDER if name in present]
    order += sorted(name for name in present if name not in order and name not in {
        '.git', 'node_modules', 'target', 'design-artifacts', 'code-reviews',
    })
    tree = [node(name) for name in order]

    files: list[str] = []

    def collect(nodes: list[dict]) -> None:
        for n in nodes:
            if n['type'] == 'file':
                files.append(n['id'])
            else:
                collect(n.get('children', []))

    collect(tree)

    sources = {rel: snapshot(rel) for rel in SNAPSHOT_LIMIT if (REPO / rel).exists()}

    data = (
        '/* Generated by make-workspace-data.py — real Clay workspace snapshot.\n'
        '   Do not edit by hand; re-run the script after the repo changes. */\n'
        'window.CLAY_WORKSPACE = '
        + json.dumps(
            {
                'root': REPO.name,
                'path': '/workspace',
                'status': 'Connected',
                'files': files,
                'tree': tree,
                'sources': sources,
            },
            indent=1,
        )
        + ';\n'
    )
    for out in OUT_DIRS:
        (out / 'workspace-data.js').write_text(data, encoding='utf-8')
        print(f'wrote {out / "workspace-data.js"}')
    print(f'{len(files)} files · {len(sources)} snapshotted')


if __name__ == '__main__':
    main()
