import {
  defineButton,
  defineEditorView,
  defineFlex,
  defineLabel,
  defineList,
  definePanel,
  defineStack,
  publishTree,
} from "clay:sdui";

const root = defineFlex({
  id: "runtime-smoke-root",
  direction: "row",
  children: [
    definePanel({
      id: "runtime-smoke-workspace-panel",
      title: "Runtime Smoke Workspace",
      children: [
        defineStack({
          id: "runtime-smoke-stack",
          children: [
            defineLabel({ id: "runtime-smoke-status", text: "Runtime SDUI smoke ready" }),
            defineButton({
              id: "runtime-smoke-refresh",
              label: "Refresh",
              action: { commandId: "workspace.refresh", arguments: { force: true } },
            }),
            defineList({
              id: "runtime-smoke-documents",
              items: [
                {
                  id: "runtime-smoke-active-document",
                  label: "Document 1",
                  detail: "Generated by tests/fixtures/configuration/runtime-sdui/init.js",
                  action: { commandId: "document.open_recent" },
                },
              ],
            }),
          ],
        }),
      ],
    }),
    defineEditorView({ id: "runtime-smoke-editor", documentId: 1, expectedVersion: 1 }),
  ],
});

await publishTree(root);
